services:
  backend:
    build:
      context: ./backend
      dockerfile: DockerfileProd
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - FRONTEND_URL=http://y.xyz.com
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerfileProd
    ports:
      - "80:80"
    environment:
      - REACT_APP_ENV=development
      - REACT_APP_BACKEND_URL=http://x.xyz.com
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 
