services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-development}
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    env_file:
      - ./backend/.env.${NODE_ENV:-development}
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_ENV=${NODE_ENV:-development}
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_ENV=${NODE_ENV:-development}
    env_file:
      - ./frontend/.env.${NODE_ENV:-development}
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 
